# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-09 05:31
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ExampleItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('summary', models.TextField()),
                ('img', models.ImageField(blank=True, upload_to='media/')),
                ('start_date', models.DateField(default=datetime.date.today)),
            ],
        ),
        migrations.CreateModel(
            name='ExperienceItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('subtitle', models.CharField(max_length=50)),
                ('thumbnail', models.ImageField(blank=True, upload_to='media/')),
                ('tech_used', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('start_date', models.DateField(default=datetime.date.today)),
                ('end_date', models.DateField(default=datetime.date.today)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ImageListField',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='media/')),
            ],
        ),
        migrations.CreateModel(
            name='CommercialGames',
            fields=[
                ('experienceitem_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='personal_site.ExperienceItem')),
            ],
            options={
                'abstract': False,
            },
            bases=('personal_site.experienceitem',),
        ),
        migrations.CreateModel(
            name='Hobbies',
            fields=[
                ('experienceitem_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='personal_site.ExperienceItem')),
            ],
            options={
                'abstract': False,
            },
            bases=('personal_site.experienceitem',),
        ),
        migrations.CreateModel(
            name='Projects',
            fields=[
                ('experienceitem_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='personal_site.ExperienceItem')),
            ],
            options={
                'abstract': False,
            },
            bases=('personal_site.experienceitem',),
        ),
        migrations.CreateModel(
            name='WorkExperience',
            fields=[
                ('experienceitem_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='personal_site.ExperienceItem')),
            ],
            options={
                'abstract': False,
            },
            bases=('personal_site.experienceitem',),
        ),
        migrations.AddField(
            model_name='experienceitem',
            name='display_pictures',
            field=models.ManyToManyField(to='personal_site.ImageListField'),
        ),
    ]
