# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-15 22:18
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ExampleItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('summary', models.TextField()),
                ('img', models.ImageField(blank=True, upload_to='media/')),
                ('start_date', models.DateField(default=datetime.date.today)),
            ],
        ),
        migrations.CreateModel(
            name='ExperienceItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('thumbnail', models.ImageField(blank=True, upload_to='media/')),
                ('highlights', models.CharField(help_text='Tech used, skills learnt or lessons learnt', max_length=200)),
                ('description', models.TextField(help_text='Short and sweet summary of the experience. Use Bullet Point sentences!')),
                ('start_date', models.DateField(default=datetime.date.today)),
                ('ongoing', models.BooleanField(default=False, help_text='Is this still current and ongoing?')),
                ('end_date', models.DateField(blank=True, default=datetime.date.today, help_text='Only displayed if Ongoing is false')),
                ('organization', models.CharField(help_text='Company, Society, Group', max_length=50)),
                ('location', models.CharField(max_length=50)),
                ('ext_url', models.URLField(blank=True, help_text='Link to more information')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='GameTitle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('thumbnail', models.ImageField(blank=True, upload_to='media/')),
                ('highlights', models.CharField(help_text='Tech used, skills learnt or lessons learnt', max_length=200)),
                ('description', models.TextField(help_text='Short and sweet summary of the experience. Use Bullet Point sentences!')),
                ('start_date', models.DateField(default=datetime.date.today)),
                ('ongoing', models.BooleanField(default=False, help_text='Is this still current and ongoing?')),
                ('end_date', models.DateField(blank=True, default=datetime.date.today, help_text='Only displayed if Ongoing is false')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ImageListField',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='media/')),
            ],
        ),
        migrations.CreateModel(
            name='PersonalInterest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('thumbnail', models.ImageField(blank=True, upload_to='media/')),
                ('highlights', models.CharField(help_text='Tech used, skills learnt or lessons learnt', max_length=200)),
                ('description', models.TextField(help_text='Short and sweet summary of the experience. Use Bullet Point sentences!')),
                ('start_date', models.DateField(default=datetime.date.today)),
                ('ongoing', models.BooleanField(default=False, help_text='Is this still current and ongoing?')),
                ('end_date', models.DateField(blank=True, default=datetime.date.today, help_text='Only displayed if Ongoing is false')),
                ('display_pictures', models.ManyToManyField(blank=True, help_text='Relevant images', to='personal_site.ImageListField')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PersonalProject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('thumbnail', models.ImageField(blank=True, upload_to='media/')),
                ('highlights', models.CharField(help_text='Tech used, skills learnt or lessons learnt', max_length=200)),
                ('description', models.TextField(help_text='Short and sweet summary of the experience. Use Bullet Point sentences!')),
                ('start_date', models.DateField(default=datetime.date.today)),
                ('ongoing', models.BooleanField(default=False, help_text='Is this still current and ongoing?')),
                ('end_date', models.DateField(blank=True, default=datetime.date.today, help_text='Only displayed if Ongoing is false')),
                ('display_pictures', models.ManyToManyField(blank=True, help_text='Relevant images', to='personal_site.ImageListField')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ExtracurricularExperience',
            fields=[
                ('experienceitem_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='personal_site.ExperienceItem')),
            ],
            options={
                'abstract': False,
            },
            bases=('personal_site.experienceitem',),
        ),
        migrations.CreateModel(
            name='VolunteerExperience',
            fields=[
                ('experienceitem_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='personal_site.ExperienceItem')),
            ],
            options={
                'abstract': False,
            },
            bases=('personal_site.experienceitem',),
        ),
        migrations.CreateModel(
            name='WorkExperience',
            fields=[
                ('experienceitem_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='personal_site.ExperienceItem')),
            ],
            options={
                'abstract': False,
            },
            bases=('personal_site.experienceitem',),
        ),
        migrations.AddField(
            model_name='gametitle',
            name='display_pictures',
            field=models.ManyToManyField(blank=True, help_text='Relevant images', to='personal_site.ImageListField'),
        ),
        migrations.AddField(
            model_name='experienceitem',
            name='display_pictures',
            field=models.ManyToManyField(blank=True, help_text='Relevant images', to='personal_site.ImageListField'),
        ),
        migrations.AddField(
            model_name='exampleitem',
            name='list_images',
            field=models.ManyToManyField(blank=True, to='personal_site.ImageListField'),
        ),
    ]
