# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-05 21:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('personal_site', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DisplayItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('subtitle', models.CharField(max_length=50)),
                ('thumbnail', models.ImageField(upload_to='media/')),
            ],
        ),
        migrations.CreateModel(
            name='ImageModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='media/')),
            ],
        ),
        migrations.AlterField(
            model_name='exampleitem',
            name='img',
            field=models.ImageField(upload_to='media/'),
        ),
        migrations.CreateModel(
            name='ExperienceItem',
            fields=[
                ('displayitem_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='personal_site.DisplayItem')),
                ('tech_used', models.CharField(max_length=200)),
                ('description', models.TextField()),
            ],
            bases=('personal_site.displayitem',),
        ),
        migrations.AddField(
            model_name='exampleitem',
            name='limg',
            field=models.ManyToManyField(to='personal_site.ImageModel'),
        ),
    ]
