# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-15 22:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personal_site', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('thumbnail', models.ImageField(blank=True, upload_to='media/')),
                ('external_link', models.URLField(help_text='Link external site. Inserted as an href')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
