# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-06 03:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personal_site', '0002_auto_20160505_2135'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exampleitem',
            name='limg',
        ),
        migrations.AddField(
            model_name='experienceitem',
            name='display_pictures',
            field=models.ManyToManyField(to='personal_site.ImageModel'),
        ),
    ]
