# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-16 04:54
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personal_site', '0002_contactinfo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactinfo',
            name='external_link',
            field=models.CharField(help_text='Link external site. Inserted as an href', max_length=200),
        ),
        migrations.AlterField(
            model_name='experienceitem',
            name='end_date',
            field=models.DateField(blank=True, default=datetime.date.today, help_text='Only displayed if Ongoing is false', null=True),
        ),
        migrations.AlterField(
            model_name='experienceitem',
            name='highlights',
            field=models.CharField(blank=True, help_text='Tech used, skills learnt or lessons learnt', max_length=200),
        ),
        migrations.AlterField(
            model_name='gametitle',
            name='end_date',
            field=models.DateField(blank=True, default=datetime.date.today, help_text='Only displayed if Ongoing is false', null=True),
        ),
        migrations.AlterField(
            model_name='gametitle',
            name='highlights',
            field=models.CharField(blank=True, help_text='Tech used, skills learnt or lessons learnt', max_length=200),
        ),
        migrations.AlterField(
            model_name='personalinterest',
            name='end_date',
            field=models.DateField(blank=True, default=datetime.date.today, help_text='Only displayed if Ongoing is false', null=True),
        ),
        migrations.AlterField(
            model_name='personalinterest',
            name='highlights',
            field=models.CharField(blank=True, help_text='Tech used, skills learnt or lessons learnt', max_length=200),
        ),
        migrations.AlterField(
            model_name='personalproject',
            name='end_date',
            field=models.DateField(blank=True, default=datetime.date.today, help_text='Only displayed if Ongoing is false', null=True),
        ),
        migrations.AlterField(
            model_name='personalproject',
            name='highlights',
            field=models.CharField(blank=True, help_text='Tech used, skills learnt or lessons learnt', max_length=200),
        ),
    ]
