# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-15 09:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personal_site', '0003_auto_20160509_2305'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='volunteerexperience',
            name='ext_url',
        ),
        migrations.AddField(
            model_name='workexperience',
            name='company',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='workexperience',
            name='ext_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='workexperience',
            name='location',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='experienceitem',
            name='subtitle',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
