# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-16 04:56
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personal_site', '0003_auto_20160516_0454'),
    ]

    operations = [
        migrations.AlterField(
            model_name='experienceitem',
            name='end_date',
            field=models.DateField(default=datetime.date.today, help_text='Only displayed if Ongoing is false'),
        ),
        migrations.AlterField(
            model_name='gametitle',
            name='end_date',
            field=models.DateField(default=datetime.date.today, help_text='Only displayed if Ongoing is false'),
        ),
        migrations.AlterField(
            model_name='personalinterest',
            name='end_date',
            field=models.DateField(default=datetime.date.today, help_text='Only displayed if Ongoing is false'),
        ),
        migrations.AlterField(
            model_name='personalproject',
            name='end_date',
            field=models.DateField(default=datetime.date.today, help_text='Only displayed if Ongoing is false'),
        ),
    ]
