# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-17 06:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personal_site', '0004_auto_20160516_0456'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gametitle',
            name='description',
        ),
        migrations.RemoveField(
            model_name='gametitle',
            name='display_pictures',
        ),
        migrations.RemoveField(
            model_name='gametitle',
            name='end_date',
        ),
        migrations.RemoveField(
            model_name='gametitle',
            name='highlights',
        ),
        migrations.RemoveField(
            model_name='gametitle',
            name='ongoing',
        ),
        migrations.RemoveField(
            model_name='gametitle',
            name='start_date',
        ),
        migrations.AddField(
            model_name='gametitle',
            name='external_link',
            field=models.URLField(blank=True, help_text='Link external site. Inserted as an href'),
        ),
    ]
