# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-24 05:41
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('personal_site', '0005_auto_20160517_0617'),
    ]

    operations = [
        migrations.CreateModel(
            name='Honor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name/Title/Listing of this honor', max_length=35)),
                ('date', models.DateField(default=datetime.date.today)),
            ],
        ),
        migrations.CreateModel(
            name='Award',
            fields=[
                ('honor_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='personal_site.Honor')),
                ('location', models.CharField(help_text='Where did you earn it?', max_length=40)),
                ('entity', models.CharField(help_text='What Person, Society, Conference, etc gave you the award?', max_length=40)),
            ],
            bases=('personal_site.honor',),
        ),
        migrations.CreateModel(
            name='Publication',
            fields=[
                ('honor_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='personal_site.Honor')),
                ('journal', models.CharField(max_length=50)),
                ('authors', models.CharField(max_length=200)),
                ('reference', models.CharField(help_text='Link to the publication', max_length=200)),
            ],
            bases=('personal_site.honor',),
        ),
    ]
