# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2018-01-24 07:24
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personal_site', '0009_auto_20170525_1105'),
    ]

    operations = [
        migrations.AddField(
            model_name='award',
            name='last_awarded',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name='award',
            name='recurring',
            field=models.BooleanField(default=False, help_text='Was/is this a recurring award?'),
        ),
    ]
