# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-10-28 02:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personal_site', '0010_auto_20180124_0724'),
    ]

    operations = [
        migrations.AddField(
            model_name='personalproject',
            name='app_install_link',
            field=models.URLField(blank=True, help_text='Link to a 3rd party from where the app can be installed'),
        ),
        migrations.AddField(
            model_name='personalproject',
            name='live_url',
            field=models.URLField(blank=True, help_text='Link to a running version of the app'),
        ),
        migrations.AddField(
            model_name='personalproject',
            name='sourcecode_url',
            field=models.URLField(blank=True, help_text='Link to the source code'),
        ),
    ]
